const CONFIG={whatsappNumber:"916207120625",channelUrl:"https://whatsapp.com/channel/0029VbBiWLTHbFVA9MesXj3f",videoId:"MYLRdxkfzeI"};
const SERVICES={khatiyan:{name:"पुराना खतियान",title:"खतियान निकालें",description:"पुराने खतियान के लिए उपलब्ध जानकारी भरें।",fields:[["raiyat","रैयत का नाम","रैयत / जमीन मालिक का नाम",1],["khata","खाता संख्या","खाता संख्या लिखें",1],["khesra","खेसरा / प्लॉट संख्या","खेसरा / प्लॉट संख्या लिखें",1],["page","पृष्ठ संख्या","पृष्ठ संख्या (यदि उपलब्ध हो)",0],["part","भाग संख्या","भाग संख्या (यदि उपलब्ध हो)",0]]},kewala:{name:"केवाला",title:"केवाला निकलवाएं",description:"केवाला खोजने के लिए उपलब्ध जानकारी भरें।",fields:[["raiyat","रैयत / खरीदार / विक्रेता का नाम","नाम लिखें",1],["kewalaNo","केवाला संख्या","केवाला संख्या (यदि उपलब्ध हो)",0],["year","केवाला वर्ष","वर्ष (यदि उपलब्ध हो)",0],["plot","प्लॉट / खेसरा संख्या","प्लॉट / खेसरा संख्या (यदि उपलब्ध हो)",0],["extraId","अन्य पहचान / विवरण","यदि उपलब्ध हो तो लिखें",0]]},jamabandi:{name:"जमाबंदी पंजी",title:"जमाबंदी देखें",description:"पुरानी जमाबंदी पंजी के लिए उपलब्ध जानकारी भरें।",fields:[["raiyat","रैयत का नाम","रैयत / जमीन मालिक का नाम",1],["khata","खाता संख्या","खाता संख्या लिखें",0],["jamabandi","जमाबंदी संख्या","जमाबंदी संख्या लिखें",0],["computerized","कम्प्यूटरीकृत जमाबंदी संख्या","यदि उपलब्ध हो",0],["page","पृष्ठ संख्या","पृष्ठ संख्या (यदि उपलब्ध हो)",0],["part","भाग संख्या","भाग संख्या (यदि उपलब्ध हो)",0]]},receipt:{name:"जमीन की रसीद",title:"रसीद कटवाएं",description:"जमीन की लगान/रसीद सेवा के लिए उपलब्ध जानकारी भरें।",fields:[["raiyat","रैयत का नाम","रैयत / जमीन मालिक का नाम",1],["khata","खाता संख्या","खाता संख्या (यदि उपलब्ध हो)",0],["khesra","खेसरा / प्लॉट संख्या","खेसरा / प्लॉट संख्या (यदि उपलब्ध हो)",0],["jamabandi","जमाबंदी संख्या","जमाबंदी संख्या (यदि उपलब्ध हो)",0],["receiptYear","रसीद का वर्ष","वर्ष (यदि उपलब्ध हो)",0]]}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const popup=$("#channelPopup"),modal=$("#serviceModal"),form=$("#serviceForm"),dynamic=$("#dynamicLandFields"),selected=$("#selectedService");
$("#year").textContent=new Date().getFullYear();setTimeout(()=>{if(localStorage.getItem("abs_channel_popup_closed")!=="1")popup.style.display="grid"},900);$("#closePopup").onclick=()=>{popup.style.display="none";localStorage.setItem("abs_channel_popup_closed","1")};
$("#menuBtn").onclick=()=>$("#mobileNav").classList.toggle("open");$$('#mobileNav a').forEach(a=>a.onclick=()=>$("#mobileNav").classList.remove("open"));
function openService(key){const s=SERVICES[key]||SERVICES.khatiyan;selected.value=key;$("#modalTitle").textContent=s.title;$("#modalDescription").textContent=s.description;$("#landFieldsTitle").textContent=s.name+" की जानकारी";dynamic.innerHTML=s.fields.map(f=>`<label>${f[1]}<input name="${f[0]}" ${f[3]?"required":""} placeholder="${f[2]}"></label>`).join("");resetSteps();modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}
function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.style.overflow=""}$$('[data-service]').forEach(b=>b.onclick=()=>openService(b.dataset.service));$$('[data-close-modal]').forEach(x=>x.onclick=closeModal);document.onkeydown=e=>{if(e.key==="Escape")closeModal()};
function resetSteps(){form.reset();$("#successState").hidden=true;form.style.display="block";$$('.form-step').forEach((x,i)=>x.classList.toggle('active',i===0));$$('.progress span').forEach((x,i)=>x.classList.toggle('active',i===0));$("#sameWhatsapp").checked=false;$("#selectedService").value=selected.value}
function validateStep(n){const step=$(`.form-step[data-step="${n}"]`);let ok=true;step.querySelectorAll("[required]").forEach(i=>{i.classList.remove("bad");if(!i.value.trim()){i.classList.add("bad");ok=false}});if(n===3){const m=step.querySelector('[name="mobile"]');if(!/^[6-9]\d{9}$/.test(m.value.trim())){m.classList.add("bad");alert("कृपया सही 10 अंकों का मोबाइल नंबर दर्ज करें।");ok=false}}if(!ok&&n!==3)alert("कृपया सभी जरूरी जानकारी भरें।");return ok}function showStep(n){$$('.form-step').forEach(x=>x.classList.toggle('active',+x.dataset.step===n));$$('.progress span').forEach((x,i)=>x.classList.toggle('active',i<n))}$$('.next-step').forEach(b=>b.onclick=()=>{const n=+b.closest('.form-step').dataset.step;if(validateStep(n))showStep(n+1)});$$('.prev-step').forEach(b=>b.onclick=()=>showStep(+b.closest('.form-step').dataset.step-1));
$("#sameWhatsapp").onchange=e=>{const w=form.querySelector('[name="whatsapp"]'),m=form.querySelector('[name="mobile"]');w.value=e.target.checked?m.value:"";w.readOnly=e.target.checked};form.querySelector('[name="mobile"]').oninput=e=>{if($("#sameWhatsapp").checked)form.querySelector('[name="whatsapp"]').value=e.target.value};
const clean=v=>String(v||"").trim()||"उपलब्ध नहीं";function appId(k){const d=new Date(),date=String(d.getFullYear()).slice(-2)+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0'),p={khatiyan:'KHT',kewala:'KEW',jamabandi:'JMB',receipt:'RCT'}[k],key='abs_'+date;let n=+(localStorage.getItem(key)||0)+1;localStorage.setItem(key,n);return `ABS-${p}-${date}-${String(n).padStart(4,'0')}`}
form.onsubmit=e=>{e.preventDefault();if(!validateStep(3))return;const k=selected.value,s=SERVICES[k],d=Object.fromEntries(new FormData(form).entries()),id=appId(k),L=["नया भूमि रिकॉर्ड आवेदन",`Application ID: ${id}`,`सेवा: ${s.name}`,"","जमीन का स्थान:",`जिला: ${clean(d.district)}`,`अंचल / प्रखंड: ${clean(d.circle)}`,`हल्का: ${clean(d.halka)}`,`मौजा / गाँव: ${clean(d.mauza)}`,"","जमीन / रिकॉर्ड की जानकारी:"];s.fields.forEach(f=>L.push(`${f[1]}: ${clean(d[f[0]])}`));L.push("","आवेदक:",`नाम: ${clean(d.applicant)}`,`मोबाइल: ${clean(d.mobile)}`,`WhatsApp: ${clean(d.whatsapp||d.mobile)}`,`अतिरिक्त जानकारी: ${clean(d.extra)}`,"","कृपया मेरे आवेदन की आगे की प्रक्रिया के बारे में जानकारी दें।");$("#applicationId").textContent=id;$("#sendWhatsapp").href=`https://wa.me/${CONFIG.whatsappNumber}?text=${encodeURIComponent(L.join("\n"))}`;form.style.display="none";$("#successState").hidden=false;$$('.progress span').forEach(x=>x.classList.add('active'))};$("#newApplication").onclick=resetSteps;
